-- ============================================================
-- Creatorverse - repair script (plain statements only)
-- Run in: Supabase -> SQL Editor -> New query -> Run
--
-- Disables RLS and re-seeds the five default creators.
-- Safe to run more than once. Only the five seeded names are
-- replaced, so creators you added yourself are left alone.
-- ============================================================

-- 1. Make sure the table exists.
create table if not exists public.creators (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  name        text        not null,
  url         text        not null,
  description text        not null,
  "imageURL"  text
);

-- 2. THE USUAL CULPRIT.
-- With RLS on and no policy, the anon key reads zero rows and
-- reports no error at all - which is exactly what you were seeing.
alter table public.creators disable row level security;

-- 3. Re-seed the five. This only clears the seeded names, so any
-- creators you added yourself through the app are left alone.
delete from public.creators
where name in ('David Laid', 'Chris Bumstead', 'Dorian Yates', 'Lex Little', 'Adam Yu');

insert into public.creators (name, url, description, "imageURL") values
  (
    'David Laid',
    'https://www.youtube.com/@DavidLaid',
    'Latvian-born American bodybuilder whose teenage transformation series turned him into one of the most-watched lifters online. His videos lean into honest, unglamorous training footage and long-horizon thinking about physique development.',
    ''
  ),
  (
    'Chris Bumstead',
    'https://www.youtube.com/@ChrisBumstead',
    'Canadian bodybuilder and six-time Classic Physique Mr. Olympia. CBum documents contest prep, off-season training, and the day-to-day grind behind an elite physique, including the parts most highlight reels leave out.',
    ''
  ),
  (
    'Dorian Yates',
    'https://www.youtube.com/@DorianYatesOfficial',
    'Six-time Mr. Olympia from 1992 to 1997 and the architect of high-intensity Blood and Guts training. Now a coach and interviewee, Dorian is the best living argument for brutally short, brutally hard sessions over endless volume.',
    ''
  ),
  (
    'Lex Little',
    'https://www.youtube.com/@LexLittle',
    'Bodybuilding creator posting training sessions, physique updates, and gym vlogs. Worth following for the unfiltered look at consistent, week-after-week work rather than one-off transformation content.',
    ''
  ),
  (
    'Adam Yu',
    'https://www.youtube.com/@AdamYu',
    'Fitness creator covering training, nutrition, and the realities of building a physique alongside a normal life. A grounded counterweight to the extremes elsewhere in the gym corner of the internet.',
    ''
  );

-- 4. Confirm. You should get five rows back.
select id, name from public.creators order by id;
