-- ============================================================
-- Creatorverse — Supabase schema + seed
-- Paste this whole file into: Supabase dashboard -> SQL Editor -> New query -> Run
-- ============================================================

-- 1. Table -----------------------------------------------------
-- NOTE: "imageURL" is quoted so Postgres keeps the camelCase name.
-- The React app reads/writes that exact key, so don't rename it.

create table if not exists public.creators (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  name        text        not null,
  url         text        not null,
  description text        not null,
  "imageURL"  text
);

-- 2. Row Level Security ----------------------------------------
-- The prework asks for RLS OFF so the anon key can read/write freely.
-- This is fine for a class project. Do NOT do this on a real app.

alter table public.creators disable row level security;

-- 3. Realtime --------------------------------------------------

alter publication supabase_realtime add table public.creators;

-- 4. Seed data -------------------------------------------------
-- Paste your own image links into "imageURL" — the app renders a
-- styled monogram tile automatically wherever the field is empty.

insert into public.creators (name, url, description, "imageURL") values
  (
    'David Laid',
    'https://www.youtube.com/@DavidLaid',
    'Latvian-born American bodybuilder whose teenage transformation series turned him into one of the most-watched lifters online. His videos lean into honest, unglamorous training footage and long-horizon thinking about physique development.',
    ''
  ),
  (
    'Chris Bumstead',
    'https://www.youtube.com/@ChrisBumstead',
    'Canadian bodybuilder and six-time Classic Physique Mr. Olympia. "CBum" documents contest prep, off-season training, and the day-to-day grind behind an elite physique — including the parts most highlight reels leave out.',
    ''
  ),
  (
    'Dorian Yates',
    'https://www.youtube.com/@DorianYatesOfficial',
    'Six-time Mr. Olympia (1992–1997) and the architect of high-intensity "Blood and Guts" training. Now a coach and interviewee, Dorian is the best living argument for brutally short, brutally hard sessions over endless volume.',
    ''
  ),
  (
    'Lex Little',
    'https://www.youtube.com/@LexLittle',
    'Bodybuilding creator posting training sessions, physique updates, and gym vlogs. Worth following for the unfiltered look at consistent, week-after-week work rather than one-off transformation content.',
    ''
  ),
  (
    'Adam Yu',
    'https://www.youtube.com/@AdamYu',
    'Fitness creator covering training, nutrition, and the realities of building a physique alongside a normal life. A grounded counterweight to the extremes elsewhere in the gym corner of the internet.',
    ''
  );
